### ISSUE TITLE
Underline for selected bracket in Caladan Dawn theme looks like a warning

### ISSUE THREAD

**Issue by lukwol** [Anvell/intellij-dune-theme#7]
<img width="303" alt="Screenshot 2023-05-09 at 12 41 57" src="https://github.com/Anvell/intellij-dune-theme/assets/2930137/29370d5c-3d62-4abe-b1f1-b6f3ab6c6f71">

**Comment by Anvell** [comment]
Fixed by 3fd52471a140817bc3acd3ec14a3f166489f7376.
